version: "3"
services:
  Fresh:
    image: gameservers/teamfortress2
    ports:
      - 27015:27015
      - 27015:27015/udp
    env_file: tf2.env
    volumes:
      - /mnt/data/tf2:/home/steamsrv/tf2
    container_name: "terraria_fresh"
    restart: unless-stopped
    tty: true
    stdin_open: true
