version: "3"
services:
  teamfortress2:
    image:  nicholasaa/teamfortress2  
    ports:
      - 27015:27015
      - 27015:27015/udp
    env_file: tf2.env
    volumes:
      - tf2data:/home/steamsrv/tf2
    container_name: "team_fortress_2"
    hostname: "team_fortress_2"
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks: 
      - tf2
networks: 
  tf2:
    external:
      name: vm_nw
volumes:
  tf2data:
    external:
      name: teamfortress2
