version: "3"
services:
        Fresh:
                image: beardedio/terraria:vanilla-latest
                ports:
                        - "7776:7777"
                environment:
                        world: Fresh.wld
                volumes:
                                                                              - /mnt/data/terraria/Fresh:/config
                                                                                    container_name: "terraria_fresh"
                                                                                        restart: unless-stopped
                                                                                            tty: true
                                                                                                stdin_open: true
