apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: tf2data
  name: tf2data-pv
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  capacity:
    storage: 5Gi
  storageClassName: local-storage
  local:
    path: /mnt/kube/tf2
  claimRef:
    name: tf2data-claim
    namespace: default
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - node/as-r610
status: {}
